services:
  - type: web
    name: e-voting-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: voting-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: voting-db
    databaseName: voting_db
    user: voting_user
    plan: free